### ISSUE TITLE
Timezone conversion issue, (goes wrong direction)

### ISSUE THREAD

**Issue by jisaacks** [spencermountain/spacetime#284]
Here is an example:

```javascript
const z = 'America/New_York'
const a = spacetime('03/14/2021, 1:59 AM', z) // The last minute of the timezone
const b = spacetime('03/14/2021, 2:00 AM', z)

// This is correct.
a.format('iso')
// got: "2021-03-14T01:59:00.000-05:00"

// This is also correct
a.add(1, 'minute').format('iso')
// got: "2021-03-14T03:00:00.000-04:00"

// this is wrong
b.format('iso')
// got: "2021-03-14T01:00:00.000-05:00"
// expecting "2021-03-14T03:00:00.000-04:00"
```

The hour is subtracted (goes from 2 to 1 during the time change) but it should be added (go from 2 to 3)

**Comment by spencermountain** [comment]
hey @jisaacks thanks for the issue. 
My gut says it's another example of #235 - this is a tricky case where using native js Date objects for the calculation - it's a chicken and the egg issue. I'll check it out today, to confirm
I've got a fix for this, and hope to release it sometime in may, but no promises.
cheers

**Comment by jisaacks** [comment]
Great thanks, I am subscribed to that one too.

Also thanks so much for this library I been wanting something like this for years.

I actually built my own (eerily similar) but it relied on `Intl`, don't understand how you did it without it!

**Comment by spencermountain** [comment]
haha, thanks. I have woken up in the night thinking _'wait, how-the...'_
Like, there may be a conceptual reason why this should not work, and I just haven't realized it yet.
Been hoping the [temporal](https://tc39.es/proposal-temporal/docs/) folks just solve-everything and we can just go to the beach.

ok, since you seem like the worlds-best githubber, let me try to bait you to help - 

[Here](https://github.com/spencermountain/spacetime/blob/master/plugins/dst/src/calc.js) is an early attempt to formalize the **'2nd sunday of march'** folk-patterns. 
* The EU does last Sunday in March 
* Mexico does First Sunday in April
I've looked pretty hard, and I don't believe anybody has formalized this before. It's crazy. [This website](http://www.webexhibits.org/daylightsaving/g.html) kinda goes through them.
If we could write a function `guessDstDate(iana, year)` that returned an epoch, it would fix 235, and avoid having to republish new dst dates every year.
Let me know!
cheers

**Comment by spencermountain** [comment]
merging with #235  ->
