### ISSUE TITLE
Zeropad timezone offset

### ISSUE THREAD

**Issue by mattbucci** [spencermountain/spacetime#31]
Hey I was using the unix format "MM d, h:mm a" and I would have expected it to read "Nov 7th, 11:05 am". 

Instead I got  "Nov 7th, 11:5 am". I checked through https://github.com/smallwins/spacetime/blob/master/src/methods/format/unixFmt.js and it looks like 'mm' and 'm' are equivalent, so I don't think I'm using the spec wrong.

**Comment by spencermountain** [comment]
hey Matthew! yeah, you're right about this.
i'll fix that this week, this unix-formatting stuff is really new, but you're right, it should be padding like that.

**Comment by spencermountain** [comment]
hey, got [this fixed](https://github.com/smallwins/spacetime/blob/f9131dba5cfe20705c7cf40f9a9e86863d2d0ffb/test/format.test.js#L49) now, in v2.1.2.

can you check it out? I'm a bit confused about how this oughta work.
if you do `.format('h:m')`, but the minute is 22, ... it still prints 22 right?
anyways, your example works now.
cheers

**Comment by mattbucci** [comment]
I haven't had a chance to look but yeah I think it would still print 5:22 if it was 5:22 but if it was 5:02 it would print 5:2 I think if in h:m format.

The more obvious example is hh:mm vs h:mm where it would be 05:22 and 5:22 respectively, both of which are actually valid use cases.

**Comment by nicobytes** [comment]
I have a question I was using the unix format "yyyy-MM-ddTHH:mm:ssZ"

`date.unixFmt('yyyy-MM-ddTHH:mm:ssZ');`

![screen shot 2019-02-20 at 11 29 29 am](https://user-images.githubusercontent.com/7611944/53107338-d8803b80-3502-11e9-9437-91ea128e444b.png)

But it is wrong because the timezone format should have ZeroPad.

![screen shot 2019-02-20 at 11 30 53 am](https://user-images.githubusercontent.com/7611944/53107437-049bbc80-3503-11e9-8ad1-227fdcb2629d.png)

I think it would still print:

`2019-02-20T12:29:10-0400` and `2019-02-20T11:29:20-0500`

**Comment by spencermountain** [comment]
i agree, thanks @nicobytes

**Comment by spencermountain** [comment]
#99
