### ISSUE TITLE
Add configurable start-of-the-week

### ISSUE THREAD

**Issue by ryanblock** [spencermountain/spacetime#7]
Weeks start on different days in different regions. And some folks may have totally arbitrary week needs!

**Comment by kristoferjoseph** [comment]
I agree we should have a way to do this. I feel like we should write a different module that wraps spacetime for features like this.

**Comment by MartinSpd** [comment]
Do you mean something like a new module with function (let's say `weekStarts`) with one argument (name of the country, e.g. in English) and function will find out if week starts on Saturday, Sunday or Monday?
Question is, if it should return name of the day in english or localised (or day index? - might be troublesome, when days starts differently for each country). Is this still open? I can do it. Would be helpful get some ideas from you guys.

**Comment by spencermountain** [comment]
hey @MartinSpd thanks, this one may be a little tricky for a first PR.
The first/last, start/end week stuff is a little weird at times.

To be honest, i'm not sure the best way to do this. It will require some persistent stuff, like `.extend()` and `i18n()` do - and care for differences with the Date object in js. May need some thinking and planning to do properly
cheers

**Comment by MartinSpd** [comment]
I was thinking about making array with list of countries (eventually 3 letter short form) and use the index in another array to find out which day is first day of the week. Just as concept for beginning. For example `const countries = ['United States', 'United Kingdom', 'Arab Emirates']; const firstDay = [0, 1, 6];`. I can make the main function to accept one optional argument. If no argument is set, then it would return first day of week for current location. I will also check out things you proposed.

**Comment by spencermountain** [comment]
hey, that's a clever idea. I'd love to see that data somewhere. I forgot that the UAE has such a  different work week.
Maybe this is best as a separate plugin, or library. I think it would be a really useful thing. Have you seen the [plugin system](https://github.com/spencermountain/spacetime#extendingplugins)? It's not very well documented, but may be a good application.

I would worry about this:
```js
let s = spacetime.now('Canada/Eastern').startOf('week') //monday
s.goto('asia/dubai').startOf('week')//different
```
I think doing that would be unexpected, or too clever/sneaky.

**Comment by spencermountain** [comment]
i mean, I think i would prefer something like this:
```js
spacetime.config({
  weekStart:'sunday',
})
spacetime.now('Canada/Eastern').startOf('week') //sunday
spacetime.now('asia/dubai').startOf('week') //sunday
```
what do you think?

**Comment by MartinSpd** [comment]
I wouldn't set all on one day. I will look into it and when I will have some progress I let you know. As a first step I create simple day determination by returning day index (based on arrays described above). Then I will try to create something using plugin system as you proposed.

**Comment by craigpaul** [comment]
@spencermountain Do we have a way of doing this right now or are we stuck with Sunday as the first day for the time being?

**Comment by spencermountain** [comment]
yeah, sorry @craigpaul 

i guess the only place it appears right now is in ` startOf('week')` and `endOf('week')`.

... i mean, `.next()`, `.last()`, and `.add()`, `.subtract()` are just an indifferent 7 days.

and `startOf('year')` doesn't care either ....

for now, you'll just need to do `.startOf('week').add(2, 'days')`.

I think an implementation will only effect these methods - which makes it seem a lot more doable, now that i say that out loud.

**Comment by craigpaul** [comment]
@spencermountain Thats fair, we can definitely work around it on our end, just figured I'd check in. Thanks buddy! Loving the library btw!

**Comment by spencermountain** [comment]
hey, i just implemented this, it was way easier than i thought it would be.
```js
  let s = spacetime.now()
  s = s.weekStart('thursday')
  s = s.startOf('week')
  s.dayName()
  // 'thursday'
```
let me know if it breaks anything

in `5.9.0`

**Comment by craigpaul** [comment]
Fantastic! Thanks @spencermountain 👍 Definitely did not expect this to happen to soon! 😄

**Comment by MartinSpd** [comment]
And what about using [spacetime-week](https://github.com/spencermountain/spacetime-week) as `peerDependency` for this function?

**Comment by spencermountain** [comment]
hey @MartinSpd yeah, i've added `spacetime-week`  on the spacetime readme, so we should expect some users (and issues!).

yeah, we should (in my opinion) create a second method on spacetime-week like, `.setWeekStart('germany')` or something that actually changes the start of the week, instead of having to set it manually.

hey, i wanted to ask you - what do you think about the library supporting timezone names, as inputs?  we currently support `germany`, but not `Europe/Berlin` - would that be possible?

yeah, in my haste i called the method `weekStart`, which is the same name are using [here](https://github.com/spencermountain/spacetime-week/blob/master/src/index.js). So maybe we should call it `getWeekStart` or something... Sorry about that.

open to suggestions. Supporting this config should make spacetime-week a lot more powerful, I'm pretty excited about it.
cheers

**Comment by MartinSpd** [comment]
hi @spencermountain that's good you put a reference to it :-) we will see where it goes. I think the discussion about when week starts in country `Xyz` might be a bit controversial, because I saw in multiple sources different data and picked those, which I think are more possible.

For example many arab countries (muslim belief) started week on Saturday, but in [one article](https://en.wikipedia.org/wiki/Workweek_and_weekend#Muslim_countries) on Wikipedia I read in some point for business reasons they changed it to Sunday as for instance United States and it left just handful of countries starting on Saturday and it's in contrary with [article](http://chartsbin.com/view/41671) I found before.

But adding this method for setting day is a good idea and might require refactoring. Currently I keep all data about countries and days in a `JSON` (./src/data/countries.js). When a setter should be implemented it might involve database or is there a easier way?

That's an interesting idea to support both countries and time zones. I never got this idea. It requires just a minor refactoring and for example I can recognise if input is a country or time zone according to if input `string` contains a `/` symbol. I have to think about it what would be the easiest way to do it without too much code.

The thing about renaming main method to `getWeekStart` is nothing, but might be renamed, when we solve best way to set first day. I set a concept matching country to timezone by using keys for each country in `JSON` I mentioned. It's looking like this:
```
{
....
Sunday : {
....
c039: "canada",
...
}
```
and then it maps to `./zonefile/iana.js` like this:
```
...
  'america/montreal': {
...
    ctry: 'c039'
  },
...
```
I would like to keep this concept. Or it maps to time zone if the time zone name contains country name, like `canada/mountain` (and it omits mapping with country key). So, there should be way how to save both keys and countries in database or I don't know how the setter would work. I would work on in the evenings or at night, when I'm free. What do you propose for setter's logic?

**Comment by spencermountain** [comment]
yeah, that seems fair to me. It's fine to make a big gnarly json file, things shouldn't change too frequently (hopefully!).

you can always expose the json file somehow, to be set directly. Given that filesize is still small, a database shouldn't be required.

i trust your decisions on this.
